spring.application.name=chatRobot
# web server port
server.port=8080
#langchain4j????
# deepseek api-key: ${DEEPSEEK_API_KEY:}
# openai api-key: ${OPENAI_API_KEY:}
#DEEPSEEK
#langchain4j.open-ai.chat-model.base_url =https://api.deepseek.com/v1
#langchain4j.open-ai.chat-model.api-key=${DEEPSEEK_API_KEY}
#langchain4j.open-ai.chat-model.model-name=deepseek-chat
#OPENAI
#langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
#good model start
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY:}
langchain4j.open-ai.chat-model.model-name=gpt-3.5-turbo

langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY:}
langchain4j.open-ai.streaming-chat-model.model-name=gpt-3.5-turbo

#pinecone api key
langchain4j.open-ai.embedding-model.api-key=${OPENAI_API_KEY:}
langchain4j.open-ai.embedding-model.model-name=text-embedding-3-small

#good model end
#langchain4j.open-ai.chat-model.base_url =http://langchain4j.dev/demo/openai/v1
#langchain4j.open-ai.chat-model.api-key=demo
#langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
#openai log
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true

#ollama
#langchain4j.ollama.chat-model.base-url=http://localhost:11434
##langchain4j.ollama.chat-model.model-name=deepseek-r1:1.5b
#langchain4j.ollama.chat-model.model-name=llama2:latest
#langchain4j.ollama.chat-model.temperature=0.8
#langchain4j.ollama.chat-model.timeout=PT60S
#langchain4j.ollama.chat-model.log-requests=true
#langchain4j.ollama.chat-model.log-responses=true

#MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/chat_memory_db
# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/chatbot?serverTimezone=UTC
#useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Los_Angeles&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#Enabling Basic SQL Logging:
#To display the SQL statements executed by Hibernate, the default JPA provider in Spring Boot, add the following property:
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#Configuring Detailed Logging with Loggers:
#For more granular control and to include parameter binding details, configure specific loggers:
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

#log debug debug/info/error
logging.level.root=info